default_platform(:android)

platform :android do
  desc "Deploy a new version to the Alpha Google Play"
  lane :alpha do
	upload_to_play_store(track: 'alpha', aab: 'app/build/outputs/bundle/release/app-release.aab')
  end
end